################################################################################
# HOMELAB
################################################################################

include:
    #############################################################################
    # NGINX (CORE)
    #############################################################################
    - apps/postgres.yaml # PostgreSQL (Shared Database)
    - apps/mariadb.yaml # Mariadb (Shared Database)

    - apps/personal-apps.yaml
    - apps/socket-proxy.yaml # Docker Socket Proxy (Security)

    #############################################################################
    # MEDIA
    #############################################################################

    - apps/plex.yaml # Plex (Media Server)
    - apps/media-stack.yaml # Sonarr, Radarr, Bazarr, Flaresolverr, Lidarr, Prowlarr, Readarr (Media Server)
    - apps/overseerr.yaml # Overseerr (Media Requests)
    - apps/tautulli.yaml # Tautulli (Plex Analytics)
 
    #############################################################################
    # UTILITIES
    #############################################################################

    - apps/watchtower.yaml #  Watchtower (Container Updating)
    - apps/meilisearch.yaml # Meilisearch (Shared Database)
    - apps/nginx-reverse-proxy.yaml # Nginx Reverse Proxy
    - apps/prometheus.yaml # Prometheus
    - apps/gitlab.yaml # Gitlab
    - apps/mqtt.yaml 

    #############################################################################
    # MISCELLANEOUS
    #
    # * Note the existing services that are disabled by default.
    #############################################################################

    - apps/umami.yaml # Umami Analytics
    - apps/healthchecks.yaml # Healthchecks (Monitoring)
    # - apps/matrix.yaml # Matrix (Chat)
    - apps/sentry.yaml
    - apps/local-email.yaml # Local Email (Postfix, OpenDKIM, Amavis, PostfixAdmin, mostly for services that need to send email; everthing is internal and not exposed to the internet)
    #- apps/windows.yaml 

################################################################################
# NETWORK CONFIGURATION
################################################################################

networks:
    docker:
        driver: bridge
    internal:
        driver: bridge
    public:
        driver: bridge
    
