#######################################
# HEALTHCHECKS (STATUS MONITORING)
#######################################

services:
    healthchecks:
        container_name: healthchecks
        image: lscr.io/linuxserver/healthchecks:latest
        profiles: ["miscellaneous", "all"]
        env_file:
            - ${DOCKER_DIRECTORY}/.env
        volumes:
            - ${DOCKER_DIRECTORY}/appdata/healthchecks:/config
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        security_opt:
            - no-new-privileges:true
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
        networks:
            internal:
