services:
  # You'll need to install your drivers for ollama to work properly.
  #
  ollama:
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/ollama:/root/.ollama
    container_name: ollama
    tty: true
    restart: unless-stopped
    networks:
      internal:
    image: ollama/ollama:latest
    privileged: true
    devices:
        - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/open-webui:/app/backend/data
    depends_on:
      - ollama
    networks:
      internal:
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped