services:
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/mailpit/data:/data
    ports:
      - 8025:8025
    environment:
      MP_MAX_MESSAGES: 500000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      internal:
