include: 
 - ./postgres.yaml
 - ./redis.yaml

services:
  synapse:
    image: ghcr.io/element-hq/synapse:latest
    user: 1000:1000
    restart: unless-stopped
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/matrix/synapse/config:/data:rw
      - ${DOCKER_DIRECTORY}/appdata/matrix/synapse/ext/shared_secret_authenticator.py:/usr/local/lib/python3.12/site-packages/shared_secret_authenticator.py
      - ${DOCKER_DIRECTORY}/appdata/matrix/synapse/storage:/matrix-media-store-parent
    networks:
      internal:
    environment:
      SYNAPSE_CONFIG_DIR: /data
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
    depends_on:
      homelab-redis:
        condition: service_started
      matrix-postgres:
        condition: service_healthy

  element-web:
    image: vectorim/element-web:latest
    restart: unless-stopped
    user: 1000:1000
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:80/version || exit 1"]
      start_period: "5s"
      interval: "15s"
      timeout: "5s"
    networks:
      internal:
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/matrix/client-element/config.json:/app/config.json:rw
    depends_on:
      matrix-postgres:
        condition: service_completed_successfully
  matrix-postgres:
    image: postgres:16.2
    user: 999:999
    restart: unless-stopped
    networks:
      internal:
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/matrix/postgres:/var/lib/postgresql:rw
      - ${DOCKER_DIRECTORY}/scripts/create-databases.sh:/docker-entrypoint-initdb.d/create-databases.sh

    # These will be used in homeserver.yaml later on
    environment:
     - POSTGRES_DB=matrix
     - POSTGRES_USER=matrix
     - POSTGRES_PASSWORD=${MATRIX_POSTGRES_PASSWORD}
     - POSTGRES_MULTIPLE_DATABASES=synapse,matrix    
    
    healthcheck:
        test:
            [
                CMD-SHELL,
                "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB}",
            ]
        interval: 5s
        timeout: 15s
        retries: 5
