# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#######################################
# POSTGRESQL (DATABASE)
#######################################

services:
  homelab-meilisearch:
    container_name: homelab-meilisearch
    image: getmeili/meilisearch:latest
    volumes:
        - ${DOCKER_DIRECTORY}/appdata/homelab-mariadb:/meili_data
    networks:
      - internal
    healthcheck:
      test:
        - CMD
        - wget
        - --no-verbose
        - --spider
        - http://homelab-meilisearch:7700/health
      retries: 3
      timeout: 5s
