services:
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/mqtt/config:/mosquitto/config:rw
      - ${DOCKER_DIRECTORY}/appdata/mqtt/data:/mosquitto/data:rw
      - ${DOCKER_DIRECTORY}/appdata/mqtt/log:/mosquitto/log:rw
    restart: unless-stopped
    networks: 
      internal: