# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#######################################
#OAUTH (GOOGLE OAUTH FOR ADMIN)
#######################################
include: 
 - ./mariadb.yaml

services:
  aut.hair.web:
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/aut.hair/.env:/var/www/html/.env
      - ${DOCKER_DIRECTORY}/appdata/aut.hair/start.sh:/var/www/html/start.sh
    networks:
      internal:
    container_name: aut.hair.web
    image: ghcr.io/austinkregel/aut.hair:latest
    command: bash /var/www/html/start.sh
    depends_on:
      homelab-mariadb:
        condition: service_healthy
        restart: true
