#######################################
# OVERSEERR (DOWNLOAD REQUESTS)
#######################################

services:
    overseerr:
        container_name: overseerr
        image: lscr.io/linuxserver/overseerr:latest
        profiles: ["media", "all"]
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        volumes:
            - ${DOCKER_DIRECTORY}/appdata/overseerr:/config
        security_opt:
            - no-new-privileges:true
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
