#######################################
# PLEX (MOVIES AND TV SERVER)
#######################################

services:
    plex:
        container_name: plex
        image: lscr.io/linuxserver/plex:latest
        profiles: ["media", "all"]
        network_mode: host
        volumes:
            - ${DOCKER_DIRECTORY}/appdata/plex:/config
            - ${TV_DIR}:/tv
            - ${MOVIE_DIR}:/movies
            - ${MUSIC_DIR}:/music
            - ${PLEX_TRANSCODE_DIR:-/tmp}:/transcode
            - ${BOOKS_DIR}:/books
        devices:
            - /dev/dri:/dev/dri
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
            VERSION: docker
            PLEX_CLAIM: ${PLEX_CLAIM}
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
