# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#######################################
# POSTGRESQL (DATABASE)
#######################################

services:
    homelab-postgres:
        container_name: homelab-postgres
        image: postgres:16.2
        profiles: ["utilities", "all"]
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_DB: ${POSTGRES_DB:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_MULTIPLE_DATABASES:-}    
            PGPASSWORD: '${POSTGRES_PASSWORD:-secret}'
        networks:
            - internal
        volumes:
            - ${DOCKER_DIRECTORY}/appdata/homelab-postgres:/var/lib/postgresql/data
            - ${DOCKER_DIRECTORY}/scripts/create-databases.sh:/docker-entrypoint-initdb.d/create-databases.sh
        restart: always
        healthcheck:
            test:
                [
                    CMD-SHELL,
                    "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-postgres}",
                ]
            interval: 5s
            timeout: 15s
            retries: 5
