# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#######################################
# REDIS (DATABASE)
#######################################
services:
  homelab-redis:
    container_name: homelab-redis
    image: redis:alpine
    profiles: ["utilities", "all"]
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
        - ${DOCKER_DIRECTORY}/appdata/homelab-redis/data:/data:rw
        - ${DOCKER_DIRECTORY}/appdata/homelab-redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
    networks:
        internal:
    healthcheck:
      test:
      - CMD
      - redis-cli 
      - ping
      retries: 3
      timeout: 5s