# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#######################################
# REDIS (DATABASE)
#######################################
services:
  homelab-redis:
    container_name: homelab-redis
    image: redis:alpine
    volumes:
        - ${DOCKER_DIRECTORY}/appdata/homelab-redis:/data:rw
    networks:
        internal:
    ports:
      - 6379:6379
    healthcheck:
      test:
      - CMD
      - redis-cli 
      - ping
      retries: 3
      timeout: 5s