# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
####################################
# Umami Analytics
####################################
include: 
 - ./postgres.yaml


services:
    umami:
        image: ghcr.io/umami-software/umami:postgresql-latest
        platform: linux/amd64
        container_name: umami
        networks:
            - internal
        profiles: ["miscellaneous", "all"]
        environment:
            DATABASE_URL: postgresql://umami:${POSTGRES_PASSWORD}@homelab-postgres:5432/umami
            DATABASE_TYPE: postgresql
            APP_SECRET: ${UMAMI_APP_SECRET:-umami}
        depends_on:
            homelab-postgres:
                condition: service_healthy
                restart: true
        restart: always
        healthcheck:
            test: [CMD-SHELL, "curl http://umami:3000/api/heartbeat"]
            interval: 5s
            timeout: 5s
            retries: 5